config/routes.rb
Gratch03::Application.routes.draw do

  devise_for :users
  root :to => 'gratches#index'

  resources :gratches

end

app/models/gratch.rb
class Gratch < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gratches_controller.rb
class GratchesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_gratch, only: [:show, :edit, :update, :destroy]

  # GET /gratches
  # GET /gratches.json
  def index
    @gratches = Gratch.all
  end

  # GET /gratches/1
  # GET /gratches/1.json
  def show
  end

  # GET /gratches/new
  def new
    @gratch = Gratch.new
  end

  # GET /gratches/1/edit
  def edit
  end

  # POST /gratches
  # POST /gratches.json
  def create
    @gratch = Gratch.new(gratch_params)

    respond_to do |format|
      if @gratch.save
        format.html { redirect_to @gratch, notice: 'Gratch was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gratch }
      else
        format.html { render action: 'new' }
        format.json { render json: @gratch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gratches/1
  # PATCH/PUT /gratches/1.json
  def update
    respond_to do |format|
      if @gratch.update(gratch_params)
        format.html { redirect_to @gratch, notice: 'Gratch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gratch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gratches/1
  # DELETE /gratches/1.json
  def destroy
    @gratch.destroy
    respond_to do |format|
      format.html { redirect_to gratches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gratch
      @gratch = Gratch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gratch_params
      params.require(:gratch).permit(:host_id, :bro1_id, :bro2_id, :bro3_id, :bro4_id, :datetime, :city, :adress, :zipcode)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gratches_helper.rb
module GratchesHelper
end

app/views/gratches/_form.html.erb
<%= form_for(@gratch) do |f| %>
  <% if @gratch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gratch.errors.count, "error") %> prohibited this gratch from being saved:</h2>

      <ul>
      <% @gratch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :host_id %><br>
    <%= f.number_field :host_id %>
  </div>
  <div class="field">
    <%= f.label :bro1_id %><br>
    <%= f.number_field :bro1_id %>
  </div>
  <div class="field">
    <%= f.label :bro2_id %><br>
    <%= f.number_field :bro2_id %>
  </div>
  <div class="field">
    <%= f.label :bro3_id %><br>
    <%= f.number_field :bro3_id %>
  </div>
  <div class="field">
    <%= f.label :bro4_id %><br>
    <%= f.number_field :bro4_id %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br>
    <%= f.datetime_select :datetime %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :adress %><br>
    <%= f.text_field :adress %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.number_field :zipcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gratches/edit.html.erb
<h1>Editing gratch</h1>

<%= render 'form' %>

<%= link_to 'Show', @gratch %> |
<%= link_to 'Back', gratches_path %>

app/views/gratches/index.html.erb
<h1>Gratch List</h1>

<table>
  <thead>
    <tr>
      <th>Host</th>
      <th>Bro1</th>
      <th>Bro2</th>
      <th>Bro3</th>
      <th>Bro4</th>
      <th>Datetime</th>
      <th>City</th>
      <th>Adress</th>
      <th>Zipcode</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gratches.each do |gratch| %>
      <tr>
        <td><%= gratch.host_id %></td>
        <td><%= gratch.bro1_id %></td>
        <td><%= gratch.bro2_id %></td>
        <td><%= gratch.bro3_id %></td>
        <td><%= gratch.bro4_id %></td>
        <td><%= gratch.datetime %></td>
        <td><%= gratch.city %></td>
        <td><%= gratch.adress %></td>
        <td><%= gratch.zipcode %></td>
        <td><%= link_to 'Show', gratch %></td>
        <td><%= link_to 'Edit', edit_gratch_path(gratch) %></td>
        <td><%= link_to 'Destroy', gratch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gratch', new_gratch_path %>

app/views/gratches/new.html.erb
<h1>New gratch</h1>

<%= render 'form' %>

<%= link_to 'Back', gratches_path %>

app/views/gratches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Host:</strong>
  <%= @gratch.host_id %>
</p>

<p>
  <strong>Bro1:</strong>
  <%= @gratch.bro1_id %>
</p>

<p>
  <strong>Bro2:</strong>
  <%= @gratch.bro2_id %>
</p>

<p>
  <strong>Bro3:</strong>
  <%= @gratch.bro3_id %>
</p>

<p>
  <strong>Bro4:</strong>
  <%= @gratch.bro4_id %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @gratch.datetime %>
</p>

<p>
  <strong>City:</strong>
  <%= @gratch.city %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @gratch.adress %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @gratch.zipcode %>
</p>

<%= link_to 'Edit', edit_gratch_path(@gratch) %> |
<%= link_to 'Back', gratches_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gratch03</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<div class="container">

  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <%= yield %>
</div>


</body>
</html>